### ISSUE TITLE
Is it actually working?

### ISSUE THREAD

**Issue by tom10271** [rangle/batarangle#103]
I tried to build it in company with a MacBook Air and at home with a Win 7 PC. Yet using it with a TODO app built with Angular 2 provided by todomvc.com

Here is the link:
http://todomvc.com/examples/angular2/

When I select to todo-app in Component Inspector page it only shows:
"ng is not defined"

Any ideas?

**Comment by sumitarora** [comment]
@tom10271 Did you add the debug configurations as shown in the Readme file ? https://github.com/rangle/batarangle#current-limitations

**Comment by tom10271** [comment]
Thank you for pointing out the missing step
