### ISSUE TITLE
Batarangle state doesn't update on page refresh

### ISSUE THREAD

**Issue by SethDavenport** [rangle/batarangle#114]
Steps to reproduce:

1. Run the todo-mvc-example
2. Add some tasks
3. Open batarangle: the components are shown as expected.
4. Refresh the browser window

The tasks go away in the app (because the example app isn't persistent).  However batarangle still shows all the components from the previous run. 

Workaround: close and reopen dev tools.

**Comment by midroid** [comment]
yes, same problem, workaround works

**Comment by sumitarora** [comment]
@midroid we are working on that target is to fix it with beta.3 fixes

**Comment by xinrui-ma** [comment]
This issue still exist on my newest version of batarangle? Any idea?

**Comment by sumitarora** [comment]
@xinrui-ma If you are using latest version of Angular and Batarangle this shouldn't be the case if you reload your angular 2 application.
