### ISSUE TITLE
Remove tsd and use typings instead

### ISSUE THREAD

**Issue by sumitarora** [rangle/batarangle#140]

**Comment by sumitarora** [comment]
@igor-ka can you elaborate this

**Comment by igor-ka** [comment]
@sumit  @vanessayuenn `tsd` has been deprecated in favour of `typings` we should use that on Batarangle as well. `typings` takes a slightly different approach to `tsd` so we need to read up on it. However, I transitioned one project to it already, so if you have questions I should be able to help.
