### ISSUE TITLE
Conditionally enable the panels based on the presence of the angular framework

### ISSUE THREAD

**Issue by igor-ka** [rangle/batarangle#17]
Provide logic to find out if Angular 2.0 is used within the context of the inspected application.

If Angular 2.0 is present, show our component inspector and the angular panel, otherwise show nothing.

Need to investigate on how to do that, the answer might come from the angular team. This is inspired by the similar check present in React Dev Tools extension.

**Comment by bertrandk** [comment]
Fixed with #54
