### ISSUE TITLE
Uncaught ReferenceError: getAllAngularRootElements is not defined

### ISSUE THREAD

**Issue by alexkibler** [rangle/batarangle#185]
When using Batarangle in the angular/angular2-seed systemjs branch, I get the above error, and none of my components appear in batarangle. If I disable batarangle, the error goes away, so I'm certain it's related somehow.  Let me know if there's anything else I can provide to make it easier to debug. The error is at  backend.js:23620

**Comment by sumitarora** [comment]
@alexkibler `getAllAngularRootElements` was added in beta.8 of Angular2. Batarangle has been updated to work with it.

**Comment by davelander** [comment]
@sumitarora just a comment - on latest ang2, 
if I have dev tools open with batarangle enabled and then I reload the page, I get this same error.

But if dev tools are not enabled when i reload, and then I open the dev tools, batarang resolves getAllAngularRootElements successfully.

**Comment by sumitarora** [comment]
@davelander Thanks, Will look into the issue

**Comment by sumitarora** [comment]
@davelander I have checked the latest version and it seems to be working. Can you tell me how did u installed Batarangle?

**Comment by davelander** [comment]
downloaded from the io site, dragged and dropped the crx file into the extensions window

**Comment by JMoli** [comment]
@sumitarora I am also experiencing this issue. I had to enable developer mode and then drag and drop the crx file for the extension to be usable. It should be noted that I am attempting to debug an ionic2 app and my issue may be unrelated.

**Comment by sumitarora** [comment]
@JMoli It works beta.8 onwards `getAllAngularRootElements` was added in beta.8. Which version of Angular you are on?

**Comment by alexkibler** [comment]
I just manually update to beta.9 and it seems to be working for me now.

**Comment by JMoli** [comment]
@sumitarora Confirmed was running beta.6 manually updated to beta.8 works great! Awesome extension thanks!

**Comment by MarkPieszak** [comment]
Just received this error today actually, did it come back somehow?

**Comment by canda** [comment]
+1
