### ISSUE TITLE
Navigating away from Angular 2 apps with Batarangle opened triggers an error

### ISSUE THREAD

**Issue by vanessayuenn** [rangle/batarangle#238]
Steps to reproduce: 
1. open batarangle
2. navigate to another page that's not an angular 2 app
3. see error below
![image](https://cloud.githubusercontent.com/assets/6842965/14117776/344d77de-f5b4-11e5-8df2-f62285c42915.png)

That is because the backend script is getting injected on every page load (see [line 17-23 in `src/content-script.ts`](https://github.com/rangle/batarangle/blob/master/src/content-script.ts#L21). Probably should add some kind of check to see if there's an angular 2 app on the page.

**Comment by mobinni** [comment]
Done

**Comment by vanessayuenn** [comment]
Resolved by #250
