### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by andrejkn** [rangle/batarangle#28]
#### Let's propose some Logo designs

![batarangle logo](https://drive.google.com/uc?export=view&amp&id=0B64DgEVawBQ5bjdWcDctN01ZNVU)

**Comment by SethDavenport** [comment]
Here's one from our blog - not specific to batarang but we could ask Chris P if he minds us repurposing it.

![Rangle Debug](http://blog.rangle.io/content/images/2015/08/Angular-Bug.jpg)

**Comment by igor-ka** [comment]
Hey @andrejkn and @SethDavenport, thanks so much for your input, this is really appreciated :)

@andrejkn I like the direction you are going but I think the bat could use some work. I would make it meaner, but this is just my personal preference. Let's see what other Ranglers say and expand on it.

I would use the image that @SethDavenport provided for the talk, and then work on then expand on the concept suggested by @andrejkn

**Comment by andrejkn** [comment]
@igor-ka  I am glad that you prefer meaner bat, my initial idea was to make it like the **Batman's** logo. Something like the one below... However, definitely we need a designer to do this better, I am just throwing out ideas.
![batarangle logo](https://drive.google.com/uc?export=view&amp&id=0B64DgEVawBQ5SkZfOFUxd0VyWk0)

**Comment by josepot** [comment]
@andrejkn If I were you I would [be careful with that logo](http://www.bbc.com/sport/0/football/30143924).

**Comment by andrejkn** [comment]
@josepot that's good to know :-) 
I was just giving a suggestion and hopefully some of our designers can come up with something interesting but different from the original batman logo

**Comment by winkerVSbecks** [comment]
I used this for the demo. It's open source: http://iconmonstr.com/bug-track-icon

<img width="562" alt="screen shot 2015-10-21 at 10 12 41 am" src="https://cloud.githubusercontent.com/assets/42671/10639099/5965066e-77dc-11e5-9bdb-82005062451e.png">

**Comment by igor-ka** [comment]
@andrejkn @josepot @SethDavenport @winkerVSbecks @bertrandk @vanessayuenn 

What if we use the open source bug and put it instead of the letter A on the angular shield?

**Comment by cpangan** [comment]
Hey guys, just got caught up with the thread and I agree with @josepot that we should try to avoid the batarangle to avoid any copyright infringement issues that may occur as a result. @andrejkn That second version is exactly what I was thinking but as noted above, may get us into a sticky situation.

Here's a version of what @igor-ka had suggested with @winkerVSbecks input.


![batarangle-logo](https://cloud.githubusercontent.com/assets/11467032/10888697/b0d489b4-815b-11e5-8320-ea4a34b94538.jpg)

**Comment by winkerVSbecks** [comment]
@cpangan that's awesome!

**Comment by sumitarora** [comment]
Done We have finalized logo 
![icon128](https://cloud.githubusercontent.com/assets/198247/13113728/5ebb4f6c-d55e-11e5-8a48-73fb5d906d00.png)
