### ISSUE TITLE
Show typescript sources in chrome devtools stacktrace

### ISSUE THREAD

**Issue by alexeagle** [rangle/batarangle#34]
If I include sourcemaps in an app, I can open the original typescript source file and set breakpoints.
However, stacktraces still reference the .js file so clicking through those links takes me to the wrong place.
Probably a chrome issue but it seems like you guys could drive the fix?

**Comment by alexeagle** [comment]
Can post a minimal repro if that's helpful.

**Comment by bertrandk** [comment]
From what I can tell, this is an issue with Chrome.

It may be worth looking into https://github.com/stacktracejs/stacktrace-gps or https://github.com/novocaine/sourcemapped-stacktrace when we take a stab at error notification in the extension.

/cc @winkerVSbecks

**Comment by igor-ka** [comment]
Thank you for your feedback @alexeagle 

Sourcemaps in chrome extension seems to be as easy as everywhere else. There is a PR that should address this.

**Comment by winkerVSbecks** [comment]
With the new Webpack build system we have source-maps generating. I just need to link it to the file or make it inline.

**Comment by alexeagle** [comment]
We were able to generate sourcemaps with webpack - as I said, we can set
breakpoints in TypeScript files. The issue is just with presentation of the
stack trace.

**Comment by winkerVSbecks** [comment]
@alexeagle I merged PR with the Webpack build like an hour ago. Just tested break-points and `console.logs`. There are 2 levels to this:

1. Devtools where Batarangle is running
2. Devtools to debug Batarangle itself

In (1) the logs are linked to the `.ts` files. In (2) the logs don't seem to be linked to `.ts` files but, the break-points are. 

Can you confirm that?

**Comment by alexeagle** [comment]
great, that looks good from the screenshot. I don't have time to fetch the latest and verify right now, am working on other stuff. Thanks!
