### ISSUE TITLE
State normalization for directives

### ISSUE THREAD

**Issue by vanessayuenn** [rangle/batarangle#35]
NgFor & NgIf first; other directives to be followed.

**Comment by bertrandk** [comment]
These are the ones we're primarily concerned with:
- [ ] NgClass
- [ ] NgFor
- [ ] NgIf
- [ ] NgStyle
- [ ] NgSwitch
- [ ] NgSwitchWhen
- [ ] NgSwitchDefault

NgForm brings in another set:
- [ ] NgControlName,
- [ ] NgControlGroup,
- [ ] NgFormControl,
- [ ] NgModel,
- [ ] NgFormModel,
- [ ] NgForm,
- [ ] NgSelectOption,
- [ ] DefaultValueAccessor,
- [ ] NumberValueAccessor,
- [ ] CheckboxControlValueAccessor,
- [ ] SelectControlValueAccessor,
- [ ] NgControlStatus,
- [ ] RequiredValidator,
- [ ] MinLengthValidator,
- [ ] MaxLengthValidator
