### ISSUE TITLE
Provide contribution guidelines

### ISSUE THREAD

**Issue by igor-ka** [rangle/batarangle#48]
Need to think of proper guidelines documents so as to make external contributions easy, and smooth out the on-boarding experience.

**Comment by bertrandk** [comment]
As per #63:
- [ ] Add an MIT license
- [ ] Add commit message guidelines (as much as we care)
- [ ] Review that tslint is adequate and can be relied upon fully
  - I really want to avoid contributors having to revisit PRs for styleguide issues when the linter told them they were good
- [ ] Add actual, clickable, link to github issues (as the issue tracker)
- [ ] Expound on guidelines for contributions
  - just more details, especially with regards to how feature requests work
  - a solution to the "I'm new and don't even know where to get started" problem
    - the crux of the problem is that there's a lot of "out-of-band" stuff that occurs on projects (design docs, mental models, previous decisions, etc...)
    - we don't need a comprehensive solution in the PR but a dedicated "newcomer" slack/IRC channel and a paragraph directing them there might suffice

**Comment by vanessayuenn** [comment]
This is done.
