### ISSUE TITLE
Developer README

### ISSUE THREAD

**Issue by bertrandk** [rangle/batarangle#65]
_**Objective:** Eliminate issues (reported and unreported) raised by developers trying to setup a developing environment or getting the Developer Preview up and running._

## Concerns
- There are actually no explicit instructions as to how to go about making changes to the codebase.

Related: #57, #41, #60, #59

**Comment by vescogma** [comment]
Going over the repo, it seems that [CONTRIBUTING.md](https://github.com/rangle/batarangle/blob/master/CONTRIBUTING.md) already addresses these issues. If anything it seems the first place any developer would go to if they want need a more issue-related readme than the main one. We should probably just continue to use that and expand it with any other developer issues we encounter.
