### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by bertrandk** [rangle/batarangle#66]
_**Objective:** Foster an inclusive environment and lower the barrier to entry in participating to the project._

## Concerns
- Some past attempts at this have either been derailed by "controversy" or been drowned in equivocations. Needless to say, we should probably avoid this. :smirk: 
- We MUST have a contact email address.
- It'd be great if the community could be empowered to self-police (i.e. little to no formal moderation).

## Prior art
- [MINASWAN](https://en.wikipedia.org/wiki/MINASWAN)
  - More of a motto than a COD, per se, but likely the most effective thing I've ever seen.
- [The Rust Code of Conduct](https://www.rust-lang.org/conduct.html)
  - Simple, clear and concise
  - Amazing work by the Rust team
- [Citizen Code of Conduct](http://citizencodeofconduct.org/)
  - A strong template, great definitions
- [Node.js's Inclusivity Working Group](https://github.com/nodejs/inclusivity)
  - Early days but it's definitely a novel approach (there have been similar attempts but not quite like this, it seems)
  - We have no need for this level of formalism but their focus on specificity and actionability is worth paying attention to (see: https://github.com/nodejs/inclusivity/pull/22)

**Comment by winkerVSbecks** [comment]
@bertrandk Atom uses this: http://contributor-covenant.org/version/1/2/0/

**Comment by bertrandk** [comment]
Ohhh...I'll take a look. Thanks.

**Comment by vanessayuenn** [comment]
resolved by #200
