### ISSUE TITLE
Cleanup/Refactor Developer Preview

### ISSUE THREAD

**Issue by bertrandk** [rangle/batarangle#69]
_**Objective:** Clean house and lay down the foundation for the next phase of features._

## Concerns
- [ ] Simplify directory structure @igor-ka 
- [x] Remove unused code features @vanessayuenn 
- [x] Document remaining code @vanessayuenn 
- [x] Fix ts compiler warnings @vanessayuenn #41 
- [ ] Write unit tests
- ~~Update type declarations (see angular/angular#5248 & [wiki](https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages))~~

**Comment by igor-ka** [comment]
@bertrandk typings are already picked up from node_modules for batarangle (not the example app though), so there is nothing to do in that regard.

**Comment by bertrandk** [comment]
Thanks @igor-ka, updated description.

**Comment by vanessayuenn** [comment]
Closing this one - the remaining cleanup work will be tracked in #139 #141 #142
