### ISSUE TITLE
Build more examples

### ISSUE THREAD

**Issue by bertrandk** [rangle/batarangle#70]
_**Objective:** Provide a playground of different kinds of Angular application and a showcase of the tool's capabilities across them._

## Concerns
- The goal should be to demonstrate a variety of data-flows (one-way/two-way), data structures (immutable collections, streams, primitives, etc...)
  - A potential consideration of different backends (e.g. REST, Firebase, Relay, etc...) might also be interesting – especially later on
- I'd be nice if the "barrier to play" here was extremely
  - I'm not against us hosting them
  - Support for ['Deploy to Heroku'](https://devcenter.heroku.com/articles/heroku-button) might also prove helpful to experimentation
- We probably need some Angular1 applications too...

/cc @AbdellaToronto

**Comment by bertrandk** [comment]
Might be a good opportunity to run [Angular CLI](http://ngcli.github.io/) through it's paces.

**Comment by sumitarora** [comment]
@bertrandk We have kitchen-sink app to try Batarangle features. Do we need any more examples? Should I deploy it to Heroku?

**Comment by bertrandk** [comment]
I think that's good. We don't necessarily need to deploy it to heroku ourselves I think. The idea was that if we had the "deploy to heroku" button, others could do so themselves and have a running sample app in one click as opposed to clone the repo, reading the docs, installing dependencies, etc....

**Comment by bertrandk** [comment]
*cloning

/cc @sumitarora

**Comment by sumitarora** [comment]
@bertrandk They can do it using our starters so we can close issue?

**Comment by bertrandk** [comment]
Yup.
