### ISSUE TITLE
Investigate why browserify is needed for test to run properly

### ISSUE THREAD

**Issue by vanessayuenn** [rangle/batarangle#75]
Without browserify, failing tests cause indefinite hanging. (See comments in #72). Since the tests are already getting bundled by webpack, running it through browserify is redundant. Find out how we can take out browserify without tests hanging.

**Comment by itanex** [comment]
@bertrandk What was the reason that this was deferred?

**Comment by bertrandk** [comment]
Mostly a matter of priority @itanex given it's not very severe (zero user impact really...just an oddity). If you want to take a crack at it, I'd love the help. I'm also available if you have any questions.

**Comment by itanex** [comment]
Gotcha. I assumed as much. I have a bunch of work on my plate now, this seems like fun to add to it. I will see what I can do.

**Comment by mobinni** [comment]
I'm working on this issue and found a fix. Pull request will be out soon

**Comment by mobinni** [comment]
This issue has been solved by PR #207
