### ISSUE TITLE
More condensed nested component view

### ISSUE THREAD

**Issue by timkindberg** [rangle/batarangle#84]
The view on the left that shows all the components as gray blocks nested within each other feels too large and spread out. With deep complex hierarchies or long repeated lists it's going to be tiresome scrolling around the list while keeping a sense of where you are within the list.

Have you considered any other layouts?
- HTML tags, similar to react dev tools
- collapsable shorter blocks, similar to Mac OS Finder List view

**Comment by bertrandk** [comment]
As a matter of fact, we're addressing that right now. The problem, simply stated, revolves not just around how best to display the hierarchical relationship between components but also how to show contextual information about those components. 

HTML tags do the job wrt to hierarchies, with sufficient indentation, but limit the type of information we can communicate. XML-ish tags don't provide much in terms of affordances if we would, say, like to subtlety indicate which component in the list had triggered an uncaught exception. 

Collapsable shorter blocks are much more interesting. It's also probable that we don't need to have **all** components visible at once if we provide a good navigation story.

It may make sense to separate those two objectives and provide different views if it doesn't lead to too much clutter, maybe. In any case, the design and UX work is ongoing so we'll see. :smile: 

I'll keep this open as a tracking issue.

**Comment by vanessayuenn** [comment]
@timkindberg check out the new design we've just implemented! Closing this issue for now, but more feedback is always welcome. :)

**Comment by timkindberg** [comment]
Will check soon!
