### ISSUE TITLE
Cannot resolve module rxjs/*

### ISSUE THREAD

**Issue by drew-moore** [rangle/batarangle#86]
As of [this commit in alpha-48](https://github.com/angular/angular/commit/5514dc19d9779fb6b0d7bbae8268dc21dd1dde39), Angular is importing RxJS modules via `rxjs` rather than `@reactive/rxjs`. [#45](https://github.com/rangle/batarangle/pull/85) did not update Batarangle's dependencies accordingly, resulting in this warning on `npm install`:

`angular2@2.0.0-beta.0 requires a peer of rxjs@5.0.0-beta.0 but none was installed.`

`npm run build` then barfs on `Cannot resolve module rxjs/*` for all rxjs modules, and the resultant extension is nonfunctional. 

Changing the import in `package.json` and updating the import statements in `/backend/base`, `/frontend/dispatcher/dispatcher` and `/stores/abstract-store` seems to resolve the problem and results in a successful build, with all tests still passing. Submitting PR with these changes now.

**Comment by SethDavenport** [comment]
I can repro this with node 5/npm 3, but not with node 4/npm 2.
